spring:
  application:
    name: trap-iot-service

  threads:
    virtual:
      enabled: true # Enable virtual threads for the application

  output:
    ansi:
      enabled: always # Enable ANSI colors in the console output

  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: catchcare-iot

mqtt:
  url: tcp://${MQTT_BROKER_HOST:localhost}:${MQTT_BROKER_PORT:1883}
  client-id: trap-iot-client
  inbound-topics:
    catchcare/trap/status      # e.g. trap activated, trap closed
  outbound-topics:
    catchcare/trap/command     # e.g. take-photo

logging:
  level:
    root: INFO
#    org.springframework.integration: DEBUG

server:
  port: 8081